export const PORTUGUESE_STOPWORDS = new Set([
  'a', 'ao', 'aos', 'aquela', 'aquelas', 'aquele', 'aqueles', 'aquilo', 'as',
  'até', 'com', 'como', 'da', 'das', 'de', 'dela', 'delas', 'dele', 'deles',
  'depois', 'do', 'dos', 'e', 'ela', 'elas', 'ele', 'eles', 'em', 'entre',
  'era', 'eram', 'essa', 'essas', 'esse', 'esses', 'esta', 'estas', 'este',
  'estes', 'eu', 'foi', 'fomos', 'for', 'fora', 'foram', 'forem', 'formos',
  'fosse', 'fossem', 'há', 'isso', 'isto', 'já', 'lhe', 'lhes', 'lo', 'mas',
  'me', 'mesmo', 'meu', 'meus', 'minha', 'minhas', 'muito', 'na', 'nas', 'nem',
  'no', 'nos', 'nós', 'nossa', 'nossas', 'nosso', 'nossos', 'num', 'numa',
  'não', 'o', 'os', 'ou', 'para', 'pela', 'pelas', 'pelo', 'pelos', 'por',
  'qual', 'quando', 'que', 'quem', 'se', 'seja', 'sejam', 'sejamos', 'sem',
  'ser', 'será', 'serão', 'seria', 'seriam', 'seu', 'seus', 'só', 'somos',
  'sou', 'sua', 'suas', 'também', 'te', 'tem', 'tendo', 'tenha', 'tenham',
  'tenhamos', 'tenho', 'ter', 'teu', 'teus', 'ti', 'tinha', 'tinham', 'tive',
  'tivemos', 'tiver', 'tivera', 'tiveram', 'tiverem', 'tivermos', 'tivesse',
  'tivessem', 'tu', 'tua', 'tuas', 'um', 'uma', 'umas', 'uns', 'vai', 'vamos',
  'você', 'vocês', 'vos', 'vossa', 'vossas', 'vosso', 'vossos',
  'ok', 'sim', 'nao', 'ola', 'olá', 'bom', 'boa', 'dia', 'obrigado', 'obrigada',
  'pois', 'então', 'entao', 'aqui', 'ali', 'lá', 'la', 'ainda', 'agora',
  'sempre', 'nunca', 'tudo', 'nada', 'algo', 'alguém', 'algum', 'alguma',
  'alguns', 'algumas', 'outro', 'outra', 'outros', 'outras', 'mesmo', 'mesma',
  'mesmos', 'mesmas', 'tal', 'tais', 'tanto', 'tanta', 'tantos', 'tantas',
  'quanto', 'quanta', 'quantos', 'quantas', 'cada', 'todo', 'toda', 'todos',
  'todas', 'qualquer', 'quaisquer', 'mais', 'menos', 'muito', 'muita', 'muitos',
  'muitas', 'pouco', 'pouca', 'poucos', 'poucas', 'bem', 'mal', 'assim',
  'onde', 'aonde', 'donde', 'porque', 'porquê', 'pra', 'pro', 'pros', 'pras',
  'sobre', 'sob', 'ante', 'após', 'desde', 'contra', 'perante', 'através',
  'durante', 'mediante', 'segundo', 'conforme', 'consoante', 'salvo', 'exceto',
  'afora', 'fora', 'dentro', 'acima', 'abaixo', 'atrás', 'frente', 'lado',
  'meio', 'volta', 'redor', 'cima', 'baixo', 'diante', 'defronte', 'junto',
  'perto', 'longe', 'além', 'aquém', 'através', 'faz', 'fazer', 'feito',
  'sendo', 'sido', 'estar', 'estou', 'está', 'estamos', 'estão', 'estive',
  'esteve', 'estivemos', 'estiveram', 'estava', 'estávamos', 'estavam',
  'estivera', 'estivéramos', 'esteja', 'estejamos', 'estejam', 'estivesse',
  'estivéssemos', 'estivessem', 'estiver', 'estivermos', 'estiverem',
  'hei', 'há', 'havemos', 'hão', 'houve', 'houvemos', 'houveram', 'havia',
  'havíamos', 'haviam', 'houvera', 'houvéramos', 'haja', 'hajamos', 'hajam',
  'houvesse', 'houvéssemos', 'houvessem', 'houver', 'houvermos', 'houverem',
  'haverei', 'haverá', 'haveremos', 'haverão', 'haveria', 'haveríamos',
  'haveriam', 'serei', 'será', 'seremos', 'serão', 'seria', 'seríamos',
  'seriam', 'terei', 'terá', 'teremos', 'terão', 'teria', 'teríamos', 'teriam',
  'ficheiro', 'revelado', 'media', 'omitted', 'imagem', 'omitida', 'anexado'
]);
